### ISSUE TITLE
There are RT tickets

### ISSUE THREAD

**Issue by eserte** [heiseonline/perl-sentry-sdk#1]
Please see https://rt.cpan.org/Ticket/Display.html?id=134348 (for example).

**Comment by pmb0** [comment]
Thanks for reporting. All issues should be fixed in v1.0.9. I don't know how to update (or disable) that RT ticket thing.

**Comment by eserte** [comment]
You should be able to login with your PAUSE credentials, I think.

As the preferred issue tracker is now correctly setup (previously it was not so) no new issues should appear there.
