### ISSUE TITLE
Undeclared dependencies

### ISSUE THREAD

**Issue by eserte** [heiseonline/perl-sentry-sdk#12]
The following dependencies seem to be undeclared in Sentry-SDK-v1.0.19:
* CGI::Application
* CGI

**Comment by pmb0** [comment]
Is there a way to declare optional dependencies in perl? These dependencies exist only because of the (optional to use) `CGI::Application::Plugin::Sentry` plugin.

**Comment by pmb0** [comment]
Ok, found [https://metacpan.org/pod/CPAN::Meta::Spec#optional_features](this). Should be fixed with https://github.com/heiseonline/perl-sentry-sdk/commit/dc6eaf2e644316c89e25c0d743be5eb0ad8174f0
