### ISSUE TITLE
t/stacktrace-frame.t fails

### ISSUE THREAD

**Issue by eserte** [heiseonline/perl-sentry-sdk#29]
The test suite fails on all of my smoker systems:
```
...
t/severity.t ....................... ok
bless( {
  "_cache" => bless( {}, 'Mock::Sentry::Cache' )
}, 'Sentry::SourceFileRegistry' )
t/source-file-registry.t ........... ok

#   Failed test 'Sentry::Stacktrace::Frame correctly identifies in-app frames'
#   at t/stacktrace-frame.t line 36.
# Looks like you failed 1 test of 8.
t/stacktrace-frame.t ............... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/8 subtests 
t/stacktrace.t ..................... ok
...
```

**Comment by pmb0** [comment]
This should (actually) be fixed in the latest version. Not?

**Comment by eserte** [comment]
There's still mostly red on http://matrix.cpantesters.org/?dist=Sentry-SDK+1.3.8
Interestingly it's only my smokers with fail reports, the ones by BINGOS and Gregor have pass reports.

**Comment by eserte** [comment]
This line looks fishy:
https://github.com/heiseonline/perl-sentry-sdk/blob/master/lib/Sentry/Stacktrace/Frame.pm#L16
So probably it fails with CPAN.pm, as the build dir is somewhere under ~/.cpan/build/...
BINGOS is using CPANplus and Gregor cpanminus, so they were not affected.

**Comment by pmb0** [comment]
Hello and thanks for the feedback -- the tests should now run in a stable manner (v1.3.9)

**Comment by eserte** [comment]
Yes, https://fast2-matrix.cpantesters.org/?dist=Sentry-SDK%201.3.9 looks better now.
