### ISSUE TITLE
Handling of Async routes in the Mojo plugin

### ISSUE THREAD

**Issue by rabbiveesh** [heiseonline/perl-sentry-sdk#4]
# The Problem
Currently, if your route is async, when the Sentry integration tries to wrap it for tracing purposes, it ends up with no status code.
This is b/c when the `around_dispatch` hook uses `$next` to pass the action to the default dispatcher, it starts the action and returns the promise. The action hasn't finished by the time our `around_dispatch` hook fires.

# A solution
In my $work code, I changed it up a little to `await` the returned promise if it's `await` compatible (there's a SHOUTY method API for things that can be awaited, see the source for Mojo::Promise). However, to do so, you  can't use Try::Tiny, b/c try-ing needs special handilng with async (from what I understand).

I could provide a patch, just not sure if you want the extra dependency. 

# Another option
The code which captures errors could provide a second error catching + resolution path in the event that the action was async. If you want, i could write this patch too.

**Comment by pmb0** [comment]
Hi, we do not use asynchronous code in Perl. It would be great if you provide the patch. The further dependency is not a problem from my point of view.

**Comment by rabbiveesh** [comment]
Cool, would love to contribute my patch.

I'm realizing something first, though.

How should the transaction be stored? What I mean is that since the route is async, the server may go on to some other task while waiting. It looked to me (please correct me if I'm wrong) that all tracing is done via a global object? So how can I store a reference to one particular transaction on the controller?

If that was a bit incoherent, I'll try and motivate this with a pain point I'm having. Right now, when I get my error logs on Sentry.io, I get a lot of breadcrumbs that have nothing to do with my request cycle (like piles upon piles of DB traces from minion workers polling, if that even makes sense). I think that's b/c the way the breadcrumbs are added to any trace or transaction isn't quite respecting the request-response cycle. If this is really a seperate issue, then we can break it out ot a new issue + have the discussion at length.

**Comment by rabbiveesh** [comment]
In the end in my personal version of this I use a combination of `Future::AsyncAwait` and `Syntax::Keyword::Dynamically` to handle this. I'm not sure if it's too hacky, so I'm going to see if I can get some feedback on it. I'll open a PR sometime soon as a draft, and I'll try and get some review.
