### ISSUE TITLE
"curfile" is not exported by the Mojo::File module

### ISSUE THREAD

**Issue by eserte** [heiseonline/perl-sentry-sdk#9]
t/sdk.t fails on a few of my smokers like this:
```
"curfile" is not exported by the Mojo::File module
Can't continue after import errors at t/sdk.t line 3.
BEGIN failed--compilation aborted at t/sdk.t line 3.
t/sdk.t ................ 
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run 
```

I think this happens if Mojolicious is too old, so probably the minimum prereq version for Mojolicious should be set.

**Comment by pmb0** [comment]
Thanks for reporting. Fixed in https://github.com/heiseonline/perl-sentry-sdk/commit/e25f4380b9222332bd1c1a1568d3baaaba6f2ab7
